# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build 
    - run: npm test --if-present
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: 'prod'
        # Directory containing files to upload
        path: 'dist'
        
    - name: Azure Blob Storage Upload
      uses: bacongobbler/azure-blob-storage-upload@v1.0.0
      with:
          # The name of the directory you want to upload
          source_dir: 'dist'
          # The name of the storage account container these assets will be uploaded to
          container_name: $web
          # The connection string for the storage account
          connection_string: ${{ secrets.connection_string }}
          # extra arguments that can be passed to `az storage blob upload-batch`. Useful for passing flags like `--pattern` or `--destination-path`
         
        
      env:
        CI: true
